language: php

php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3

sudo: false

install:
  - composer update --no-interaction --prefer-lowest

script:
  - vendor/bin/phpunit

after_script:
  - php vendor/bin/coveralls --verbose
  - CODECLIMATE_REPO_TOKEN=4a5c02026c25f24ff6314ad888d40491ad64b2347c9ea3e985b541389404d438 ./vendor/bin/test-reporter
